// Simple mock for apiService to avoid network calls in tests.
export const apiService = {
  signup: async () => ({ token: 'mock-token' }),
  login: async () => ({ token: 'mock-token' }),
  verifyToken: async () => ({ valid: true }),
  getMaterials: async () => [],
  createMaterial: async (material: any) => material,
  updateMaterial: async (_id: string, material: any) => material,
  deleteMaterial: async () => ({}),
  getQuotes: async () => [],
  createQuote: async (quote: any) => quote,
  updateQuote: async (_id: string, quote: any) => quote,
  deleteQuote: async () => ({}),
  getClients: async () => [],
  createClient: async (client: any) => client,
  updateClient: async (_id: string, client: any) => client,
  deleteClient: async () => ({}),
  getCategories: async () => [],
  createCategory: async (category: any) => category,
  updateCategory: async (_id: string, category: any) => category,
  deleteCategory: async () => ({}),
  getSettings: async () => ({}),
  updateSettings: async (settings: any) => settings,
  setToken: () => {},
  clearToken: () => {},
  createPaymentPreference: jest.fn(async () => ({ initPoint: 'https://mercadopago.com/redirect' })),
};
